:man source: Ghosd
:man version: {revnumber}
:man manual: Ghosd Manual

= ghosd(1)

== Name

ghosd - a simple, dynamic osd

== Synopsis

*ghosd* [*-h*|*-v*]

== Description

*ghosd* is an on screen display that
reads contents from
a named pipe
and displays it
for a configured time period.

It reads
a series of commands,
each on a separate line.
If the command
requires an argument,
the argument follows the command
on the next line.

== Command Arguments

'align' ::
    Text alignment, one of 'left' 'right' or 'center'.

'bodytype' ::
    Type of content in the body area, one of 'text' or 'bar'.

'color' ::
    RGBA color in hexadecimal format.

'font' ::
    Pango font description specified as '[FAMILY-LIST] [STYLE-OPTIONS] [SIZE]'.

'geometry' ::
    Two dimensions delimited by 'x'.

'percentage' ::
    Self explanatory.

'size' ::
    Size in pixels.

'string' ::
    Line of UTF-8 encoded text. Can't contain the newline character '\n'.

'time' ::
    Time duration, in miliseconds.

== Commands

=== General

'show' ::
    Displays the *ghosd* window with the current configuration.

'reset' ::
    Resets the configuration to the default values.

'quit' ::
    Terminates *ghosd*.

=== Body

==== General

'body-color <color>' ::
    Sets the color of the main body area.

'body-type <bodytype>'
    Sets what kind of content should be shown in the body area.

==== Bar

'body-bar-height <percentage>' ::
    Sets the height of the bar, as a percentage of the body area.

'body-bar-value <percentage>' ::
    Sets how much of the bar should be filled, as a percentage of the whole.

'body-bar-width <percentage>' ::
    Sets the width of the bar, as a percentage of the body area.

==== Text

'body-align <align>' ::
    Sets the alignment of the main body area.

'body-font <font>' ::
    Sets the font of the main body area.

'body-msg <string>' ::
    Sets the text of the main body area.

=== Title

'title-align <align>' ::
    Sets the alignment of the title.

'title-color <color>' ::
    Sets the color of the title.

'title-font <font>' ::
    Sets the font of the title.

'title-msg <string>' ::
    Sets the text of the title.

=== Window

'window-color <color>' ::
    Sets the color of the background.

'window-margin <size>' ::
    Sets the margin of the window.

'window-pos <geometry>' ::
    Sets the position of the window on the screen,
    as an offset of the top left window corner from the top left screen corner.

'window-size <geometry>' ::
    Sets the size of the window.

'window-timeout <time>' ::
    Sets the duration after which the window will disappear.

== Environment Variables

'GHOSD_FIFO' ::
    The path of the named pipe used for communication. If it isn't defined,
    '/tmp/ghosd-fifo'
    is used as default.

== Author

Michal Koutenský <koutak.m at gmail.com>
