= ghosd usage guide
:toc:

== Argument types

=== <align>
Text alignment, one of 'left' 'right' or 'center'.
Example: `center`

=== <color>
An RGBA color represented as eight hexadecimal characters. +
Example: `FFAA00FF`

=== <font>
Pango font description specified as '[FAMILY-LIST] [STYLE-OPTIONS] [SIZE]'. +
Example: `serif,monospace bold italic condensed 16`

=== <geometry>
Two integers delimited by `x`
representing horizontal and vertical size or offset,
in pixels. +
Example: `230x510` +
Ommiting either of the values is possible,
in which case the omitted value remains unchanged. +
Example: `230x` or `x510`

=== <size>
Size in pixels.
Example: `40`

=== <string>
A line of UTF-8 encoded text. Can't contain the newline character `\n`. +
Example: `Hello, world!`

=== <time>
A time duration, in miliseconds.
Example: `2500`

== Commands

=== General

==== show
Displays the *ghosd* window with the current configuration.

==== reset
Resets the configuration to the default values.

==== quit
Terminates *ghosd*.

=== Body

==== body-align _<align>_
Sets the alignment of the main body area.

==== body-color _<color>_
Sets the color of the main body area.

==== body-font _<font>_
Sets the font of the main body area.

==== body-msg _<string>_
Sets the text of the main body area.

=== Title

==== title-align _<align>_
Sets the alignment of the title.

==== title-color _<color>_
Sets the color of the title.

==== title-font _<font>_
Sets the font of the title.

==== title-msg _<string>_
Sets the text of the title.

=== Window

==== window-color _<color>_
Sets the color of the background.

==== window-margin _<size>_
Sets the margin of the window.

==== window-pos _<geometry>_
Sets the position of the window on the screen, as an offset of the top left window
corner from the top left screen corner.

==== window-size _<geometry>_
Sets the size of the window.

==== window-timeout _<time>_
Sets the duration after which the window will disappear.
